from pydantic import BaseModel
from typing import Optional, Dict
from uuid import uuid4


class Report(BaseModel):
    id: Optional[str] = None
    user_id: str
    kelurahan_id: str
    file_id: str
    description: str
    latitude: float
    longitude: float
    status: str = "dikirim"
    metadata: Dict = {}
    source: str = "telegram"
    tracking_code: Optional[str] = None  # auto-generated by DB trigger

    def dict_for_db(self):
        d = self.dict()
        if not d.get("id"):
            d["id"] = str(uuid4())
        # Remove None values so DB defaults/triggers can fill them
        return {k: v for k, v in d.items() if v is not None}
