KELURAHAN_OPTIONS = [
    {"id": "bausasran", "name": "Bausasran", "kemantren": "Danurejan"},
    {"id": "suryatmajan", "name": "Suryatmajan", "kemantren": "Danurejan"},
    {"id": "tegalpanggung", "name": "Tegalpanggung", "kemantren": "Danurejan"},
    {"id": "pringgokusuman", "name": "Pringgokusuman", "kemantren": "Gedongtengen"},
    {"id": "sosromenduran", "name": "Sosromenduran", "kemantren": "Gedongtengen"},
    {"id": "baciro", "name": "Baciro", "kemantren": "Gondokusuman"},
    {"id": "demangan", "name": "Demangan", "kemantren": "Gondokusuman"},
    {"id": "klitren", "name": "Klitren", "kemantren": "Gondokusuman"},
    {"id": "kotabaru", "name": "Kotabaru", "kemantren": "Gondokusuman"},
    {"id": "terban", "name": "Terban", "kemantren": "Gondokusuman"},
    {"id": "ngupasan", "name": "Ngupasan", "kemantren": "Gondomanan"},
    {"id": "prawirodirjan", "name": "Prawirodirjan", "kemantren": "Gondomanan"},
    {"id": "bumijo", "name": "Bumijo", "kemantren": "Jetis"},
    {"id": "cokrodiningratan", "name": "Cokrodiningratan", "kemantren": "Jetis"},
    {"id": "gowongan", "name": "Gowongan", "kemantren": "Jetis"},
    {"id": "prenggan", "name": "Prenggan", "kemantren": "Kotagede"},
    {"id": "purbayan", "name": "Purbayan", "kemantren": "Kotagede"},
    {"id": "rejowinangun", "name": "Rejowinangun", "kemantren": "Kotagede"},
    {"id": "kadipaten", "name": "Kadipaten", "kemantren": "Kraton"},
    {"id": "panembahan", "name": "Panembahan", "kemantren": "Kraton"},
    {"id": "patehan", "name": "Patehan", "kemantren": "Kraton"},
    {"id": "gedongkiwo", "name": "Gedongkiwo", "kemantren": "Mantrijeron"},
    {"id": "mantrijeron", "name": "Mantrijeron", "kemantren": "Mantrijeron"},
    {"id": "suryodiningratan", "name": "Suryodiningratan", "kemantren": "Mantrijeron"},
    {"id": "brontokusuman", "name": "Brontokusuman", "kemantren": "Mergangsan"},
    {"id": "keparakan", "name": "Keparakan", "kemantren": "Mergangsan"},
    {"id": "wirogunan", "name": "Wirogunan", "kemantren": "Mergangsan"},
    {"id": "ngampilan", "name": "Ngampilan", "kemantren": "Ngampilan"},
    {"id": "notoprajan", "name": "Notoprajan", "kemantren": "Ngampilan"},
    {"id": "gunungketur", "name": "Gunungketur", "kemantren": "Pakualaman"},
    {"id": "purwokinanti", "name": "Purwokinanti", "kemantren": "Pakualaman"},
    {"id": "bener", "name": "Bener", "kemantren": "Tegalrejo"},
    {"id": "karangwaru", "name": "Karangwaru", "kemantren": "Tegalrejo"},
    {"id": "kricak", "name": "Kricak", "kemantren": "Tegalrejo"},
    {"id": "tegalrejo", "name": "Tegalrejo", "kemantren": "Tegalrejo"},
    {"id": "giwangan", "name": "Giwangan", "kemantren": "Umbulharjo"},
    {"id": "muja-muju", "name": "Muja Muju", "kemantren": "Umbulharjo"},
    {"id": "pandeyan", "name": "Pandeyan", "kemantren": "Umbulharjo"},
    {"id": "semaki", "name": "Semaki", "kemantren": "Umbulharjo"},
    {"id": "sorosutan", "name": "Sorosutan", "kemantren": "Umbulharjo"},
    {"id": "tahunan", "name": "Tahunan", "kemantren": "Umbulharjo"},
    {"id": "warungboto", "name": "Warungboto", "kemantren": "Umbulharjo"},
    {"id": "pakuncen", "name": "Pakuncen", "kemantren": "Wirobrajan"},
    {"id": "patangpuluhan", "name": "Patangpuluhan", "kemantren": "Wirobrajan"},
    {"id": "wirobrajan", "name": "Wirobrajan", "kemantren": "Wirobrajan"},
]


def get_kelurahan_name(kelurahan_id: str) -> str:
    return next((k["name"] for k in KELURAHAN_OPTIONS if k["id"] == kelurahan_id), kelurahan_id)
